# Generated by Django 4.2.2 on 2024-03-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_email"),
        (
            "signature_validator",
            "0002_pdfdocumentvalidator_all_signers_verified_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturevalidator",
            name="signer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.signeruser",
            ),
        ),
    ]
